### ISSUE TITLE
Text input onchange event doesn't work properly

### ISSUE THREAD

**Issue by olegantonyan** [inesita-rb/inesita#10]
Hi! I have a trouble with onchange event

``` ruby
form  do
  input type: 'text', onchange: -> { puts 'yep!' }
end
```

When I type a text in the form nothing happens, but if I click a link to a current page in navbar then event gets fired.
Same code for checkbox works just fine.

**Comment by fazibear** [comment]
This is how this event works. http://www.w3schools.com/jsref/event_onchange.asp
