### ISSUE TITLE
allow to render passing an array argument instead of a block

### ISSUE THREAD

**Issue by elia** [inesita-rb/inesita#21]
Would be better both for performance and to simplify the syntax:

eg.

``` rb
em { "foobar" }
```

vs.

``` rb
em "foobar"
# or
em nil, "foobar"
# or
em {}, ["foobar"]
# etc.
```

I know it's not straightforward to implement, but would be useful to have

**Comment by fazibear** [comment]
This is related to `opal-virtual-dom`. Yes this will be very useful, lot of times I just forgot to use a block in this case.

**Comment by fazibear** [comment]
Hey, `opal-virtual-dom` `0.4.3` support this syntax:

```
em "ffoobar"
```

old way is still supported:

```
em { "foobar" }
```

**Comment by elia** [comment]
Great news thanks!
