### ISSUE TITLE
homepage examples do not work

### ISSUE THREAD

**Issue by fridgerator** [inesita-rb/inesita#26]
- `undefined method`ready' for nil`when using`$document.ready`
- undefined method `every' for #Clock:0x194

This looks like a very cool project, but I can't find documentation anywhere.

Is the homepage outdated?

**Comment by fazibear** [comment]
Here is a quick introduction with code examples: http://inesita-rb.github.io/, what examples don't fork for you ? Here http://inesita-playground.netlify.com/ is and example aplication and it works fine.

**Comment by fridgerator** [comment]
Ok the examples seem to work once I include the `opal-browser` gem and add the correct requires to `application.js.rb`

I was confused because those are not included by default and the code examples don't mention adding them.

Thanks

**Comment by fridgerator** [comment]
One more unrelated question.  Any idea on benchmark performance compared to angular / react / elm? 

referring to - https://evancz.github.io/todomvc-perf-comparison/

Perhaps this is more related to Opal

**Comment by fazibear** [comment]
1. True `opal-browser` was removed as a dependency. Now you can use any lib for browser integration. I guess I need to mention that examples uses `opal-browser`
2. No. I tried, but with no luck. Inesita uses `virtual-dom` under the hood. You can use http://inesita-dbmonster.netlify.com/ and browser profiling tools to compare dependency. I don't remember numbers, but is faster than react.
