### ISSUE TITLE
The dependency on slim ~> 3.0 prevents from installing Haml 5

### ISSUE THREAD

**Issue by elia** [inesita-rb/inesita#27]
That's due to different requirements on the `temple` gem.
What I'd like most is to drop the dependency on slim altogether, maybe separating the infrastructure from the core.

cc @masterkain

**Comment by fazibear** [comment]
Hi, In #28 made some changes to remove dependencies from the core. Moved all slim configuration to `config.ru`. Slim templates work fine, now trying to run haml.

**Comment by elia** [comment]
@fazibear looks great

**Comment by elia** [comment]
fixed by #28
