### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by talyssonoc** [inesita-rb/inesita#3]
Do you have any plan to implement server-side rendering? I'd be happy to try to implement it and send a PR if it is on the plans for that framework :smile:

**Comment by fazibear** [comment]
hard to say, for now I would leave Inesita as a front-end framework without any server side related stuff, so It can be used with any backend. But we can create some addons :)

**Comment by talyssonoc** [comment]
Nice! I'm gonna look for this soon!
