### ISSUE TITLE
How to access data attributes through the DSL?

### ISSUE THREAD

**Issue by jmstacey** [inesita-rb/inesita#30]
Can you provide an example of how to access HTML data attributes through the DSL.

For example, to generate this html: 
```html
<li class="dd-item" data-id="1" data-example="sample">
```

The render would need to look like what?
```ruby
def render
  li class: "dd-item" . . . . 
end
```

**Comment by jmstacey** [comment]
Eureka! The virtual DOM wrapper expects a hash parameter on the "data" or "dataset" symbol. Thought I had tried that...

```ruby
def render
  ...
    li class: "dd-item", data: { id: "1", another: "example" } ...
```

will generate the desired:
```html
<li class="dd-item" data-id="1" data-another="example">
```

@fazibear
I'll leave open for you to close incase you want to document that the DSL is provided by the wrapper in [opal-virtual-dom](https://github.com/fazibear/opal-virtual-dom/blob/master/opal/virtual_dom/dom.rb#L60) or provide an example or something.

**Comment by fazibear** [comment]
Thanks, good point, I'll add it to documentation.
