### ISSUE TITLE
Modification of class name

### ISSUE THREAD

**Issue by ghivert** [inesita-rb/inesita#37]
Hi!

I'm often using BEM to write my CSS, and so I'm doing something like this:

```ruby
div.navbar__content do
  some_stuff
end
```

But in the generated HTML, it is:

```html
<div class="navbar_content">
  some_stuff
</div>
```

Similarly, `navbar_content` get transformed to `navbar-content`.

Is there any reason to make such a change?

**Comment by fazibear** [comment]
There was a PR to make it work like this:

`navbar_content` -> `navbar-content`
`navbar__content` -> `navbar_content`

I think because of bootstrap.  So this is the way it works.
