### ISSUE TITLE
Inesita and a RESTful API?

### ISSUE THREAD

**Issue by karimmtarek** [inesita-rb/inesita#4]
Is there an example on how to hook Inesita with an API?

**Comment by fazibear** [comment]
Good point. Right now there is no any example how to use it with REST api. Let me create one :)

**Comment by karimmtarek** [comment]
Thanks :+1: 
Please let me know if you need help, I would like to get involved in the project :)

**Comment by rubyistdotjs** [comment]
:+1: I was wondering the same thing when I discovered this project yesterday.

**Comment by fazibear** [comment]
Hey, just updated example app with simple xhr request within store, checkout https://github.com/inesita-rb/playground. Hope you enjoy it.

**Comment by karimmtarek** [comment]
Thanks :+1:
