### ISSUE TITLE
insista and opal sprocket

### ISSUE THREAD

**Issue by jeezs** [inesita-rb/inesita#41]
I have  a crash when launching Inesista server, when using the latest version of opal-sprocket (0.4.2.0.11.0.3.1)

add the following file to the gem file solve the problem:
`gem 'opal-sprockets', '0.4.1.0.11.0.3.1'`

Maybe you could force this version in Inesita dependencies

**Comment by fazibear** [comment]
`opal-sprockets` version should be chosen automatically based on `sprockets` and `opal` versions. 

It can't be locked. 

Maybe try `bundle exec inesita server`

**Comment by fazibear** [comment]
Got it now, there is a problem. Will try to fix this asap.

**Comment by fazibear** [comment]
It should work now, just `bundle update` everything.

**Comment by jeezs** [comment]
Thanks for being so reactive. 
Cheers
