### ISSUE TITLE
problem with hook

### ISSUE THREAD

**Issue by jeezs** [inesita-rb/inesita#44]
Hello, 
There's a problem with the following code, when the current page is refreshed
`class Description
  include Inesita::Component

  def after_render
    `elements = document.getElementById("objid");
elements.innerHTML="new text"
`
  end

  def render
    div id: "objid", hook: hook(:_render) do
      text "text to be change!"
    end
  end
end`

when I reload the page I have the following error : TypeError: null is not an object (evaluating 'elements.innerHTML="new text"') 
The problem is even worse if the id of the object is set this way: div.objid! , hook: hook(:_render) do,...
can you help

Thanks a lot

**Comment by fazibear** [comment]
```ruby
div id: "objid", hook: hook(:_render) do
```

There is no `_render` method.

**Comment by jeezs** [comment]
sorry, dunno why this name has change maybe a bad copy paste but the problem is real, here is the code that cause the problem

```ruby
class Description
  include Inesita::Component

  def after_render
    ` elements = document.getElementById("objid");
    elements.innerHTML = "new text"`

  end

  def render
    div id: "objid", hook: hook(:after_render) do
      text "text to be change!"
    end
  end
end
```

**Comment by fazibear** [comment]
I don't think that you could find this node this way. A lot of things happening under the hood,

try something like,

```ruby
class Description
  include Inesita::Component

  def after_render(node)
    `node.innerHTML = "new text"`
  end

  def render
    div id: "objid", hook: hook(:after_render) do
      text "text to be change!"
    end
  end
end
```

I'm using hooks in this example: https://github.com/fazibear/web-audio-playground
Maybe this will help.

**Comment by jeezs** [comment]
Thank again for your precious help.
That's perfect
