### ISSUE TITLE
reactify? reactiv-ruby

### ISSUE THREAD

**Issue by MichaelSp** [inesita-rb/inesita#5]
Looks much like [reactive-ruby](https://github.com/zetachang/react.rb/tree/reactive-ruby).
But reactive-ruby is not out of the door yet.

Do you plan to support the react way of updating the DOM? That'd be really nice!

Would be great if I could replace my rails-view (or should I say template) with a proper view-system! And inesita could fill the gap.

**Comment by fazibear** [comment]
Oh, this a reason why they not update React.rb master branch. Anyway Inesita don't use React underneath. What did you mean by 'react way of updating the DOM' ?

**Comment by MichaelSp** [comment]
Afaik react works like this:
- Generate the DOM from the view-code
- Diff generated DOM with real DOM
- Apply only changes to the real DOM via smallest possible operations

Why?
- Less/No flickering 
- more performance

I guess there are good reasons to this approach. And the overwhelming success proves it.

**Comment by MichaelSp** [comment]
Oh and besides: Most of the projects use the official react.js to do the diff and update operations. I don't know if it's wise to reinvent the wheel here?!

**Comment by fazibear** [comment]
No. I don't reinvent the wheel, just use [VirtualDom](https://github.com/Matt-Esch/virtual-dom) to make things like you describe.

**Comment by MichaelSp** [comment]
Oh nice! Than never mind. You already have it all. And I'm gone drop my rails view and replace it with inesita.
Maybe you could point out the fact somewhere that inesita is doing DOM diffs.
And if you mention react you might get more attention and folks go crazy :D

**Comment by MichaelSp** [comment]
I didn't manage to setup a simple rails application. 
Would you mind creating one and link it in the examples section on the Readme?
