### ISSUE TITLE
class_name builder

### ISSUE THREAD

**Issue by fazibear** [inesita-rb/inesita#7]
Add simple helper method to build class names from hash with boolean values.

For example:

``` ruby
def render
  div class: build_class({'monday' => Time.now.monday?})
    text 'something'
  end
end
```

**Comment by rubydesign** [comment]
Here is what i wrote, creates div class/id and text in one sweep
https://github.com/salama/salama-debugger/blob/master/lib/base/element_view.rb#L22

just to have a look @fazibear , if you want

**Comment by fazibear** [comment]
Sure, but I want to avoid construction like this:

``` ruby
def render
  div class: "#{'monday' unless Time.now.monday?}" do
    text 'monday'
  end
end
```

And your soulution don't resolve a problem. Anyway, there not much difference between `class: "monday active"` and `class: ".monday.active". Better solution is:

``` ruby
def render
  div.monday.active do
    text 'monday'
  end
end
```

And this is what I want to archive with `opal-virtual-dom` gem in a future.

**Comment by fazibear** [comment]
added `class_names` helper
